// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIMsbkHq37E2Y2RbxBjBiN63m_lla8ueg',
    appId: '1:529504077370:web:f33f78ab559a6c0c68d703',
    messagingSenderId: '529504077370',
    projectId: 'unitrade-f956e',
    authDomain: 'unitrade-f956e.firebaseapp.com',
    storageBucket: 'unitrade-f956e.appspot.com',
    measurementId: 'G-1EZ4WC8RRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHDLCdGyHZSqj4XrIV2fWpqcCCjPT2sgQ',
    appId: '1:529504077370:android:c0d225009aabdf1f68d703',
    messagingSenderId: '529504077370',
    projectId: 'unitrade-f956e',
    storageBucket: 'unitrade-f956e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIO_0uCN2_fgoXW-E5xPhl8LG5ZLQKdII',
    appId: '1:529504077370:ios:77bbbc842ec62eb068d703',
    messagingSenderId: '529504077370',
    projectId: 'unitrade-f956e',
    storageBucket: 'unitrade-f956e.appspot.com',
    iosBundleId: 'com.example.unitrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIO_0uCN2_fgoXW-E5xPhl8LG5ZLQKdII',
    appId: '1:529504077370:ios:77bbbc842ec62eb068d703',
    messagingSenderId: '529504077370',
    projectId: 'unitrade-f956e',
    storageBucket: 'unitrade-f956e.appspot.com',
    iosBundleId: 'com.example.unitrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIMsbkHq37E2Y2RbxBjBiN63m_lla8ueg',
    appId: '1:529504077370:web:e93b6e6ed55cf4a968d703',
    messagingSenderId: '529504077370',
    projectId: 'unitrade-f956e',
    authDomain: 'unitrade-f956e.firebaseapp.com',
    storageBucket: 'unitrade-f956e.appspot.com',
    measurementId: 'G-DPJG2KK841',
  );
}